- name: tap extra repositories
  homebrew_tap:
    tap: homebrew/cask-fonts
    state: present
  tags: homebrew-tap

- name: install PlemolJP font
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - font-plemol-jp
    - font-plemol-jp-nf
    - font-plemol-jp-hs
  tags: plemol-jp-install
