- name: setup git config
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "Yosuke Mukasa" }
    - {name: "user.email", value: "26806017+mukasun@users.noreply.github.com" }
    - {name: "ui.color",   value: "True" }