homebrew:
  taps:
    - homebrew/cask
    - homebrew/cask-versions
    - homebrew/cask-fonts
    - homebrew/core
  casks:
    - android-studio
    - clipy
    - deepl
    - docker
    - google-cloud-sdk
    - google-chrome
    - google-japanese-ime
    - istat-menus
    - iterm2
    - itsycal
    - ngrok
    - notion
    - postman
    - rectangle
    - slack
    - spark
    - tableplus
    - visual-studio-code
    - zoom
